version: '2'
services:
  db:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=poseidon_dev
      ports:
       - "3306:3306"

  app:
#    image: amaysim/poseidon
    build: .
    restart: always
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db