default: &default
  adapter: mysql2
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  database: poseidon
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  encoding: utf8

development:
  <<: *default
  database: poseidon_dev

test:
  <<: *default
  database: poseidon_test

production:
  <<: *default
