default: &default
  adapter: mysql2
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'root' %>
  database: poseidon
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  encoding: utf8

development:
  <<: *default
  database: poseidon_dev

test:
  <<: *default
  database: <%= ENV['DB_SCHEMA'] || 'poseidon_test' %>

production:
  <<: *default
