# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 027ad05b812bcf144c3ae18fa4232f394ef3cf49a9e9870713bf60cd0afa55949780c1a47a31d6a4646fbb78b7b47d5cb0c9caffc2b57aea7f1d451580a2c989

test:
  secret_key_base: 1a0b26c0303ab5a2bb679a1b3ec3d6ea161f65be1de6171323486d3a45664a3b6aa364d091d5c66803e1014fd90e5439a7c1ad3b294d1e672e320e411bce99fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
